name: Sensor Submission
description: Fill out this form to create a new sensor and pull request.
title: "[New Sensor]: Canon C300 Mark II"
labels: [submission]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make the database better!

  - type: dropdown
    id: vendor
    attributes:
      label: Vendor
      description: Select the camera manufacturer.
      options:
        - Canon
        - Arri
        - Sony
        - Red
        - Custom
    validations:
      required: true

  - type: input
    id: custom_vendor
    attributes:
      label: Custom Vendor
      description: If you selected "Custom" above, please specify the vendor here.
      placeholder: Enter the custom vendor name
    validations:
      required: false

  - type: input
    id: camera
    attributes:
      label: Camera
      description: What's the camera name?
      value: C300 Mark II
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        ## Resolution types
        Below you'll find 10 available resolution types you can fill out.
        A very <span style='color: red;'>long</span> sentence.

        ### Field 1
        <span style="color: red;">This is important text in red.</span>

        ### Field 2
        :blue_book: **Documentation**

        Provide details for field 2 here.

        ### Field 3
        <span style="color: green;">Provide details for field 3. This text is green.</span>

        ### Field 1
        :red_circle: Important Note

        ### Field 2
        :blue_book: Documentation

        ### Field 3
        :green_heart: Environment

  - type: textarea
    id: resolution-type
    attributes:
      label: Resolution Type
      description: |
        List of resolution types and their information.
        Modify the template below to fit the new sensor information.
        If you can't find both mm and inch size for the sensor, enter one and the other will automatically be calculated.
        Focal length is optional and only used for cameras with fixed lenses, eg iPhone.
      value: |
        - Type: All
          Focal Length (optional): 
          Resolution: 4096 x 2160
          mm: 24.6 x 13.8
          inch: 0.968 x 0.543
    validations:
      required: true
