name: Sensor Submission
description: Fill out this form to create a new sensor and pull request.
title: "[New Sensor]: Canon C300 Mark II"
labels: [submission]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make the database better!

  - type: textarea
    id: references
    attributes:
      label: References
      description: Please fill out where you have found the information.
        This is just to keep track on where it all comes from.
      value: |
        Here is some good information.
        https://duckduckgo.com/?q=information&t=newext&atb=v281-1
        More on this line!
    validations:
      required: true

  - type: markdown
    attributes:
      value: "# Camera information"

  - type: dropdown
    id: vendor
    attributes:
      label: Vendor
      # description: Select the camera manufacturer.
      options:
        - Canon
        - Arri
        - Sony
        - Red
        - Custom
    validations:
      required: true

  - type: input
    id: custom_vendor
    attributes:
      label: Custom Vendor
      description: If you selected "Custom" above, please specify the vendor here.
      placeholder: Enter the custom vendor name

  - type: input
    id: camera
    attributes:
      label: Camera
      description: What's the camera's name?
      value: C300 Mark II
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: Additional Information
      description: Enter any kind of good-to-have information like lens mount, shutter type, iso range etc.
      
  - type: markdown
    attributes:
      value: |
        # Resolution types
        Below you'll find 10 available resolution types you can fill out.
        :red_circle: Type name and ether mm or inches needs to filled out or else the information isn't valid.
        If the sensor size doesn't change per resolution, name the resolution type `All` and skip entering any resolution

        If you can't find both mm and inch size for the sensor, enter one and the other will automatically be calculated.

        Focal length is optional and only used for cameras with fixed lenses, eg iPhone.

        You can ether resolution and sensor size (mm and inches) any way you want. Only the two first values found will be processed.

#### Resolution 1
  - type: markdown
    attributes:
      value: "## Resolution 1"

  - type: input
    id: name-r1
    attributes:
      label: Name
      description: ":red_circle: What's the resolution type's name?"
      value: All

  - type: input
    id: focal_length-r1
    attributes:
      label: Focal Length
      description: (Optional) What's the lens's focal length?

  - type: input
    id: resolution-r1
    attributes:
      label: Resolution
      description: (Optional)
      placeholder: 4096 x 2160
      value: 4096 x 2160

  - type: input
    id: mm-r1
    attributes:
      label: Sensor size (mm)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 24.6 x 13.8
      value: 24.6 x 13.8mm

  - type: input
    id: inches-r1
    attributes:
      label: Sensor size (inches)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 0.968 in x 0.543 in

#### Resolution 2
  - type: markdown
    attributes:
      value: "## Resolution 2"

  - type: input
    id: name-r2
    attributes:
      label: Name
      description: ":red_circle: What's the resolution type's name?"
      placeholder: "2K Anamorphic 2.39:1"

  - type: input
    id: focal_length-r2
    attributes:
      label: Focal Length
      description: (Optional) What's the lens's focal length?
      placeholder: 50mm

  - type: input
    id: resolution-r2
    attributes:
      label: Resolution
      description: (Optional)
      placeholder: 4096 x 2160

  - type: input
    id: mm-r2
    attributes:
      label: Sensor size (mm)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 24.6 x 13.8

  - type: input
    id: inches-r2
    attributes:
      label: Sensor size (inches)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 0.968 in x 0.543 in

      
#### Resolution 3
  - type: markdown
    attributes:
      value: "## Resolution 3"

  - type: input
    id: name-r3
    attributes:
      label: Name
      description: ":red_circle: What's the resolution type's name?"
      placeholder: "2K Anamorphic 2.39:1"

  - type: input
    id: focal_length-r3
    attributes:
      label: Focal Length
      description: (Optional) What's the lens's focal length?
      placeholder: 50mm

  - type: input
    id: resolution-r3
    attributes:
      label: Resolution
      description: (Optional)
      placeholder: 4096 x 2160

  - type: input
    id: mm-r3
    attributes:
      label: Sensor size (mm)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 24.6 x 13.8

  - type: input
    id: inches-r3
    attributes:
      label: Sensor size (inches)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 0.968 in x 0.543 in

      
#### Resolution 4
  - type: markdown
    attributes:
      value: "## Resolution 4"

  - type: input
    id: name-r4
    attributes:
      label: Name
      description: ":red_circle: What's the resolution type's name?"
      placeholder: "2K Anamorphic 2.39:1"

  - type: input
    id: focal_length-r4
    attributes:
      label: Focal Length
      description: (Optional) What's the lens's focal length?
      placeholder: 50mm

  - type: input
    id: resolution-r4
    attributes:
      label: Resolution
      description: (Optional)
      placeholder: 4096 x 2160

  - type: input
    id: mm-r4
    attributes:
      label: Sensor size (mm)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 24.6 x 13.8

  - type: input
    id: inches-r4
    attributes:
      label: Sensor size (inches)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 0.968 in x 0.543 in

      
#### Resolution 5
  - type: markdown
    attributes:
      value: "## Resolution 5"

  - type: input
    id: name-r5
    attributes:
      label: Name
      description: ":red_circle: What's the resolution type's name?"
      placeholder: "2K Anamorphic 2.39:1"

  - type: input
    id: focal_length-r5
    attributes:
      label: Focal Length
      description: (Optional) What's the lens's focal length?
      placeholder: 50mm

  - type: input
    id: resolution-r5
    attributes:
      label: Resolution
      description: (Optional)
      placeholder: 4096 x 2160

  - type: input
    id: mm-r5
    attributes:
      label: Sensor size (mm)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 24.6 x 13.8

  - type: input
    id: inches-r5
    attributes:
      label: Sensor size (inches)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 0.968 in x 0.543 in

      
#### Resolution 6
  - type: markdown
    attributes:
      value: "## Resolution 6"

  - type: input
    id: name-r6
    attributes:
      label: Name
      description: ":red_circle: What's the resolution type's name?"
      placeholder: "2K Anamorphic 2.39:1"

  - type: input
    id: focal_length-r6
    attributes:
      label: Focal Length
      description: (Optional) What's the lens's focal length?
      placeholder: 50mm

  - type: input
    id: resolution-r6
    attributes:
      label: Resolution
      description: (Optional)
      placeholder: 4096 x 2160

  - type: input
    id: mm-r6
    attributes:
      label: Sensor size (mm)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 24.6 x 13.8

  - type: input
    id: inches-r6
    attributes:
      label: Sensor size (inches)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 0.968 in x 0.543 in

      
#### Resolution 7
  - type: markdown
    attributes:
      value: "## Resolution 7"

  - type: input
    id: name-r7
    attributes:
      label: Name
      description: ":red_circle: What's the resolution type's name?"
      placeholder: "2K Anamorphic 2.39:1"

  - type: input
    id: focal_length-r7
    attributes:
      label: Focal Length
      description: (Optional) What's the lens's focal length?
      placeholder: 50mm

  - type: input
    id: resolution-r7
    attributes:
      label: Resolution
      description: (Optional)
      placeholder: 4096 x 2160

  - type: input
    id: mm-r7
    attributes:
      label: Sensor size (mm)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 24.6 x 13.8

  - type: input
    id: inches-r7
    attributes:
      label: Sensor size (inches)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 0.968 in x 0.543 in

      
#### Resolution 8
  - type: markdown
    attributes:
      value: "## Resolution 8"

  - type: input
    id: name-r8
    attributes:
      label: Name
      description: ":red_circle: What's the resolution type's name?"
      placeholder: "2K Anamorphic 2.39:1"

  - type: input
    id: focal_length-r8
    attributes:
      label: Focal Length
      description: (Optional) What's the lens's focal length?
      placeholder: 50mm

  - type: input
    id: resolution-r8
    attributes:
      label: Resolution
      description: (Optional)
      placeholder: 4096 x 2160

  - type: input
    id: mm-r8
    attributes:
      label: Sensor size (mm)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 24.6 x 13.8

  - type: input
    id: inches-r8
    attributes:
      label: Sensor size (inches)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 0.968 in x 0.543 in

      
#### Resolution 9
  - type: markdown
    attributes:
      value: "## Resolution 9"

  - type: input
    id: name-r9
    attributes:
      label: Name
      description: ":red_circle: What's the resolution type's name?"
      placeholder: "2K Anamorphic 2.39:1"

  - type: input
    id: focal_length-r9
    attributes:
      label: Focal Length
      description: (Optional) What's the lens's focal length?
      placeholder: 50mm

  - type: input
    id: resolution-r9
    attributes:
      label: Resolution
      description: (Optional)
      placeholder: 4096 x 2160

  - type: input
    id: mm-r9
    attributes:
      label: Sensor size (mm)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 24.6 x 13.8

  - type: input
    id: inches-r9
    attributes:
      label: Sensor size (inches)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 0.968 in x 0.543 in

      
#### Resolution 10
  - type: markdown
    attributes:
      value: "## Resolution 10"

  - type: input
    id: name-r10
    attributes:
      label: Name
      description: ":red_circle: What's the resolution type's name?"
      placeholder: "2K Anamorphic 2.39:1"

  - type: input
    id: focal_length-r10
    attributes:
      label: Focal Length
      description: (Optional) What's the lens's focal length?
      placeholder: 50mm

  - type: input
    id: resolution-r10
    attributes:
      label: Resolution
      description: (Optional)
      placeholder: 4096 x 2160

  - type: input
    id: mm-r10
    attributes:
      label: Sensor size (mm)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 24.6 x 13.8

  - type: input
    id: inches-r10
    attributes:
      label: Sensor size (inches)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 0.968 in x 0.543 in