name: Sensor Submission
description: Fill out this form to create a new sensor and pull request.
title: "[New Sensor]: Canon C300 Mark II"
labels: [submission]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make the database better!

  - type: dropdown
    id: vendor
    attributes:
      label: Vendor
      # description: Select the camera manufacturer.
      options:
        - Canon
        - Arri
        - Sony
        - Red
        - Custom
    validations:
      required: true

  - type: input
    id: custom_vendor
    attributes:
      label: Custom Vendor
      description: If you selected "Custom" above, please specify the vendor here.
      placeholder: Enter the custom vendor name
    validations:
      required: false

  - type: input
    id: camera
    attributes:
      label: Camera
      description: What's the camera's name?
      value: C300 Mark II
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        # Resolution types
        Below you'll find 10 available resolution types you can fill out.
        :red_circle: Type name and ether mm or inches needs to filled out or else the information isn't valid.
        If the sensor size doesn't change per resolution, name the resolution type `All` and skip entering any resolution

        If you can't find both mm and inch size for the sensor, enter one and the other will automatically be calculated.

        Focal length is optional and only used for cameras with fixed lenses, eg iPhone.

        You can ether resolution and sensor size (mm and inches) any way you want. Only the two first values found will be processed.

  #### Resolution 1
  - type: markdown
    attributes:
      value: |
        ## Resolution 1

  - type: input
    id: name-r1
    attributes:
      label: Name
      description: ":red_circle: What's the resolution type's name?"
      value: All

  - type: input
    id: focal_length-r1
    attributes:
      label: Focal Length
      description: (Optional) What's the lens's focal length?

  - type: input
    id: resolution-r1
    attributes:
      label: Resolution
      description: (Optional)
      placeholder: 4096 x 2160

  - type: input
    id: mm-r1
    attributes:
      label: Sensor size (mm)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 24.6 x 13.8

  - type: input
    id: inches-r1
    attributes:
      label: Sensor size (inches)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 0.968 in x 0.543 in

  #### Resolution 2
  - type: markdown
    attributes:
      value: |
        ## Resolution 2

  - type: input
    id: name-r2
    attributes:
      label: Name
      description: ":red_circle: What's the resolution type's name?"
      value: All

  - type: input
    id: focal_length-r2
    attributes:
      label: Focal Length
      description: (Optional) What's the lens's focal length?

  - type: input
    id: resolution-r2
    attributes:
      label: Resolution
      description: (Optional)
      placeholder: 4096 x 2160

  - type: input
    id: mm-r2
    attributes:
      label: Sensor size (mm)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 24.6 x 13.8

  - type: input
    id: inches-r2
    attributes:
      label: Sensor size (inches)
      description: ":red_circle: Enter at least one of mm or inches"
      placeholder: 0.968 in x 0.543 in