name: Sensor Submission

on:
  issues:
    types: [opened]

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract issue details
        id: info
        run: |
          VENDOR=$(echo "${{ github.event.issue.body }}" | awk '/### Vendor/{flag=1;next}/^###/{flag=0}flag' | tail -n +2)
          if [ "$VENDOR" == "Custom" ]; then
            VENDOR=$(echo "${{ github.event.issue.body }}" | awk '/### Custom Vendor/{flag=1;next}/^###/{flag=0}flag' | tail -n +2)
          fi
          echo "vendor=$VENDOR" >> $GITHUB_ENV

          CAMERA=$(echo "${{ github.event.issue.body }}" | awk '/### Camera/{flag=1;next}/^###/{flag=0}flag' | tail -n +2)
          echo "camera=$CAMERA" >> $GITHUB_ENV

      - name: Debug extracted data
        run: |
          echo "Event Body: ${{ github.event.issue.body }}"
          echo "Vendor: ${{ env.vendor }}"
          echo "Camera: ${{ env.camera }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Process and update JSON with Python
        run: |
          # Call the Python script to update sensors.json
          python3 scripts/update_sensors.py "${{ github.event.issue.body }}"


      - name: Create a safe branch name
        run: |
          CAMERA=$(echo '${{ env.camera }}' | tr ' ' '_' | tr -cd '[:alnum:]_')
          VENDOR=$(echo '${{ env.vendor }}' | tr ' ' '_' | tr -cd '[:alnum:]_')
          echo "branch_name=$CAMERA_$VENDOR" >> $GITHUB_ENV


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: New sensor data for ${{ env.camera }} - ${{ env.vendor }}
          labels: submission
          branch: ${{ env.branch_name }}
          branch-suffix: timestamp
          title: 'New sensor: ${{ env.vendor }} - ${{ env.camera }}'
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: |
            This pull request adds new sensor data for the camera ${{ env.camera }} by ${{ env.vendor }}.

            ${{ github.event.issue.body }}
