name: Sensor Submission

on:
  issues:
    types: [opened]

jobs:
  process_submission:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract issue details
        id: info
        run: |
          VENDOR=$(echo "${{ github.event.issue.body }}" | awk '/### Vendor/{flag=1;next}/^###/{flag=0}flag' | tail -n +2)
          echo "vendor=$VENDOR" >> $GITHUB_ENV

          CUSTOM_VENDOR=$(echo "${{ github.event.issue.body }}" | awk '/### Custom Vendor/{flag=1;next}/^###/{flag=0}flag' | tail -n +2)
          echo "custom_vendor=$CUSTOM_VENDOR" >> $GITHUB_ENV

          CAMERA=$(echo "${{ github.event.issue.body }}" | awk '/### Camera/{flag=1;next}/^###/{flag=0}flag' | tail -n +2)
          echo "camera=$CAMERA" >> $GITHUB_ENV

          RESOLUTION_TYPE=$(echo "${{ github.event.issue.body }}" | awk '/### Resolution Type/{flag=1;next}/^###/{flag=0}flag' | tail -n +2)
          echo "resolution_type<<EOF" >> $GITHUB_ENV
          echo "$RESOLUTION_TYPE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Debug extracted data
        run: |
          echo "Event Body: ${{ github.event.issue.body }}"
          echo "Vendor: ${{ env.vendor }}"
          echo "Custom Vendor: ${{ env.custom_vendor }}"
          echo "Camera: ${{ env.camera }}"
          echo "Resolution Type: ${{ env.resolution_type }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Process and update JSON with Python
        run: |
          VENDOR="${{ env.vendor }}"
          CUSTOM_VENDOR="${{ env.custom_vendor }}"
          CAMERA="${{ env.camera }}"
          RESOLUTION_TYPE="${{ env.resolution_type }}"

          if [ "$VENDOR" == "Custom" ]; then
            VENDOR="$CUSTOM_VENDOR"
          fi

          if [ -z "$VENDOR" ] || [ -z "$CAMERA" ] || [ -z "$RESOLUTION_TYPE" ]; then
            echo "Missing required fields."
            exit 1
          fi

          # Call the Python script to update sensors.json
          python3 scripts/update_sensors.py "$VENDOR" "$CAMERA" "$RESOLUTION_TYPE"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: New sensor data for ${{ env.camera }} - ${{ env.vendor }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: 'New sensor: ${{ env.vendor }} - ${{ env.camera }}'
          body: |
            This pull request adds new sensor data for the camera ${{ env.camera }} by ${{ env.vendor }}.

            ${{ github.event.issue.body }}
          labels: submission
